name: remote-workflow
on:
  workflow_dispatch:
    inputs:
      repoUrl:
        description: 'Defined in GHA as GITHUB_REPOSITORY'
        required: true
      prId:
        description: 'The ID of the PR: jq -r .pull_request.id "${GITHUB_EVENT_PATH}"'
        required: true
      prCommitId:
        description: 'The ID of the last PR commit: jq -r .pull_request.head.sha "${GITHUB_EVENT_PATH}"'
        required: true
      commentsUrl:
        description: 'The URL to comment on the PR: jq -r .pull_request.comments_url "${GITHUB_EVENT_PATH}"'
        required: true

jobs:
  devops_pipeline:
    runs-on: ubuntu-latest
    steps:
      - env:
          PAT: ${{ secrets.BOT_PAT }}
        run: |
          echo "repoUrl ${{ github.event.inputs.repoURL }}"
          echo "prId ${{ github.event.inputs.prId }}"
          echo "prCommitId ${{ github.event.inputs.prCommitId }}"
          echo "commentsUrl ${{ github.event.inputs.commentsUrl }}"

          repoUrl="${{ github.event.inputs.repoUrl }}"
          prCommitId="${{ github.event.inputs.prCommitId }}"
          commentsUrl="${{ github.event.inputs.commentsUrl }}"

          echo "==> post comment"
          payload=$( jq -R --slurp '{body: .}' <<< "Plan: OK!" )
          curl --header "Authorization: token ${PAT}" --header "Content-Type: application/json" --data "${payload}" "${commentsUrl}"
